# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-22.04"

  config.vm.synced_folder "/home/tbryant/DEV/homelab/install-scripts", "/home/vagrant/install-scripts"

  # config.ssh.username = "vagrant"
  # config.ssh.private_key_path = "~/.vagrant.d/insecure_private_key"

  # config.vm.boot_timeout = 600
end
