# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "bento/oracle-9-arm64"

  config.vm.synced_folder "/Users/timothybryant/DEV/homelab/multi-os-install-scripts", "/home/vagrant/multi-os-install-scripts"

  # config.ssh.username = "vagrant"
  # config.ssh.private_key_path = "~/.vagrant.d/insecure_private_key"

  # config.vm.boot_timeout = 600
end
